- name: Initialize of first Control Node
  hosts: master1
  become: true
  tasks:
    - name: Copy kubeadm-config.yml to node
      template:
        src: ../kubeadm-config.j2
        dest: /etc/kubernetes/kubeadm-config.yml
      tags:
        - move
    - name: Init
      shell:
        kubeadm init --config /etc/kubernetes/kubeadm-config.yml -v5 && \
        mkdir $HOME/.kube && \
        ln -s /etc/kubernetes/kubeadm-config.yml $HOME/.kube/config && \
        chown ubuntu:ubuntu $HOME/.kube && \
        chown ubuntu:ubuntu $HOME/.kube/config




